config/routes.rb
Rails.application.routes.draw do

  root "restaurants#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :restaurants do
    resources :reviews
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

  validates :name, length: {minimum: 3}, uniqueness: true
  has_many :reviews, dependent: :destroy
  belongs_to :user

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  # def build_review(review_params, current_user)
  #   parameters = review_params
  #   parameters[:user_id] = current_user.id
  #   reviews.create(parameters)
  # end
end

app/models/review.rb
class Review < ActiveRecord::Base

  validates :user, uniqueness: { scope: :restaurant, message: "has reviewed this restaurant already" }
  validates :rating, inclusion: (1..5)
  belongs_to :restaurant
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :restaurants
  has_many :reviews
  has_many :reviewed_restaurants, through: :reviews, source: :restaurant

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def has_reviewed?(restaurant)
    reviewed_restaurants.include? restaurant
  end

  def has_created?(restaurant)
    id == restaurant.user_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @user = current_user
    @restaurant = @user.restaurants.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
    unless current_user.has_created?(@restaurant)
      flash[:notice] = 'You cannot edit this restaurant'
      redirect_to restaurants_path
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    unless current_user.has_created?(@restaurant)
      flash[:notice] = 'You cannot delete this restaurant'
    else
      @restaurant.destroy
      flash[:notice] = 'Restaurant deleted successfully'
    end
    redirect_to restaurants_path
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :image)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
    if current_user.has_reviewed? @restaurant
      flash[:notice] = 'You cannot review a restaurant more than once'
      redirect_to restaurants_path
    end
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @restaurant.reviews.create(review_params)
    redirect_to restaurants_path
  end

  def review_params
    parameters = params.require(:review).permit(:thoughts, :rating)
    parameters[:user_id] = current_user.id
    parameters
  end

  def destroy
    restaurant = Restaurant.find(params[:restaurant_id])
    review = restaurant.reviews.find(params[:id])
    unless current_user.id == review.user_id
        flash[:notice] = 'You cannot delete others\' reviews'
    else
      review.destroy
    end
    redirect_to restaurants_path
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title YelpClone
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = notice
    = yield
    - if user_signed_in?
      = link_to 'Sign out', destroy_user_session_path, method: :delete
    - else
      = link_to 'Sign in', user_session_path
      = link_to 'Sign up', new_user_registration_path
      = link_to 'Sign in with Facebook', user_omniauth_authorize_path(:facebook)

app/views/restaurants/_form.html.haml
= form_for @restaurant, html: {multipart: true} do |f|
  = f.file_field :image

app/views/restaurants/edit.html.haml
= form_for @restaurant do |f|
 = f.label :name
 = f.text_field :name
 = render "form"
 = f.submit 'Update'

app/views/restaurants/index.html.haml
- if @restaurants.any?
  - @restaurants.each do |resto|
    %h2
      = link_to resto.name, restaurant_path(resto)
      = link_to "Edit #{resto.name}", edit_restaurant_path(resto)
      = link_to "Delete #{resto.name}", restaurant_path(resto), method: :delete
      = link_to "Review #{resto.name}", new_restaurant_review_path(resto)

    %h3
      Reviews for
      = resto.name
      = image_tag resto.image.url(:thumb)

    - if resto.reviews.any?
      %ul
        - resto.reviews.each do |review|
          %li
            = review.thoughts
            %strong= review.rating
            \/5
            = link_to 'Delete this review', restaurant_review_path(resto, review), method: :delete
    - else
      %p No reviews

- else
  %h1 No restaurant yet

%a(href='/restaurants/new') Add a restaurant

app/views/restaurants/new.html.haml
- if @restaurant.errors.any?
  %section#errors
    %h2
      = pluralize @restaurant.errors.count, 'error'
      prohibited this restaurant from being saved:
    %ul
      - @restaurant.errors.full_messages do |message|
        %li= message

= form_for @restaurant do |f|
  = f.label :name
  = f.text_field :name
  = f.file_field :image
  = f.submit 'Create a restaurant'

app/views/restaurants/show.html.haml
= @restaurant.name
= @restaurant.description

- if @restaurant.reviews.empty?
  %h1 No reviews yet!
- else
  - @restaurant.reviews.each do |review|
    =review.Rating
    =review.thoughts
    -if review.user_id == @id
      =link_to "Delete Review", review_path(review), method: :delete

app/views/reviews/new.html.haml
= form_for [@restaurant, @review] do |f|
  = f.label :thoughts
  = f.text_area :thoughts
  = f.label :rating
  = f.select :rating, (1..5)
  = f.submit 'Leave Review'

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/